<a href="https://colab.research.google.com/github/sumedh151/pytorch-transformer/blob/main/run_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python /content/drive/MyDrive/Colab\ Notebooks/attention\ is\ all\ you\ need/main.py

Generating train split: 100% 1659083/1659083 [00:02<00:00, 687765.29 examples/s]
Generating validation split: 100% 520/520 [00:00<00:00, 124538.23 examples/s]
Generating test split: 100% 2507/2507 [00:00<00:00, 270603.74 examples/s]
{'translation': {'en': 'Give your application an accessibility workout', 'hi': 'अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें'}}
{'en': 'Give your application an accessibility workout', 'hi': 'अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें'}
Give your application an accessibility workout
अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें
hello world
{'NUM_HEADS': 10}


In [ ]:
!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.1/542.1 kB 6.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 6.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 5.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 4.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 6.5 MB/s eta 0:00:00
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.31.0, but you have requests 2.32.3 which is incompatible.


In [ ]:
# https://www.youtube.com/watch?v=ISNdQcPhsts

import torch
import torch.nn as nn
import math
# from config import config
from datasets import load_dataset
from tokenizers import Tokenizer
from tokenizers.models import BPE
from torch.utils.data import Dataset

In [ ]:
tokenizer = Tokenizer(BPE(unk_token="[UNK]"))

dataset = load_dataset("cfilt/iitb-english-hindi", split='train')

print(dataset[0])
print(dataset[0]['translation'])
print(dataset[0]['translation']['en'])
print(dataset[0]['translation']['hi'])

if __name__ == '__main__':
    print('hello world')
    # print(config)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


{'translation': {'en': 'Give your application an accessibility workout', 'hi': 'अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें'}}
{'en': 'Give your application an accessibility workout', 'hi': 'अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें'}
Give your application an accessibility workout
अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें
hello world


In [ ]:
dataset

Dataset({
    features: ['translation'],
    num_rows: 1659083
})

In [ ]:
from datasets import load_dataset
from tokenizers import Tokenizer, models, trainers, pre_tokenizers, decoders, processors

dataset = load_dataset("cfilt/iitb-english-hindi")

# def get_texts(dataset, lang):
def get_texts(dataset):
    for example in dataset['train']['translation']:
        # yield example[lang]
        yield example['en']
        yield example['hi']

tokenizer = Tokenizer(models.BPE())

tokenizer.pre_tokenizer = pre_tokenizers.ByteLevel(add_prefix_space=False)
tokenizer.decoder = decoders.ByteLevel()
tokenizer.post_processor = processors.ByteLevel()

trainer = trainers.BpeTrainer(special_tokens=["<s>", "<pad>", "</s>", "<unk>", "<mask>"])

# tokenizer.train_from_iterator(get_texts(dataset, 'en'), trainer=trainer)
# tokenizer.train_from_iterator(get_texts(dataset, 'hi'), trainer=trainer)
tokenizer.train_from_iterator(get_texts(dataset), trainer=trainer)

tokenizer.save("iitb-english-hindi-tokenizer.json")

In [ ]:
# Encode some text
encoding = tokenizer.encode("This is a test sentence.")
print(encoding.tokens)

['i', 's', 'Ġ', 'i', 's', 'Ġ', 'a', 'Ġ', 't', 'e', 's', 't', 'Ġ', 's', 'e', 'n', 't', 'e', 'n', 'c', 'e']


In [ ]:
tokenizer.get_vocab_size()

24

In [ ]:
# Load the trained tokenizer
tokenizer = Tokenizer.from_file("iitb-english-hindi-tokenizer.json")

# Encode some text
encoding = tokenizer.encode("This is a test sentence.")
print(encoding.tokens)

# Decode back to text
decoded_text = tokenizer.decode(encoding.ids)
print(decoded_text)

['This', 'Ġis', 'Ġa', 'Ġtest', 'Ġsentence', '.']
This is a test sentence.


In [ ]:
# Load the trained tokenizer
tokenizer = Tokenizer.from_file("iitb-english-hindi-tokenizer.json")

# Encode some text
encoding = tokenizer.encode("This is a test sentence.")
print(encoding.tokens)

# Decode back to text
decoded_text = tokenizer.decode(encoding.ids)
print(decoded_text)

['This', 'Ġis', 'Ġa', 'Ġtest', 'Ġsentence', '.']
This is a test sentence.


In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['translation'],
        num_rows: 1659083
    })
    validation: Dataset({
        features: ['translation'],
        num_rows: 520
    })
    test: Dataset({
        features: ['translation'],
        num_rows: 2507
    })
})

In [ ]:
class CustomTranslationDataset(Dataset):
    def __init__(self, split='train'):
        self.img_labels = pd.read_csv(annotations_file)

    def __len__(self):
        return len(self.img_labels)

    def __getitem__(self, idx):
        img_path = os.path.join(self.img_dir, self.img_labels.iloc[idx, 0])
        image = read_image(img_path)
        label = self.img_labels.iloc[idx, 1]
        if self.transform:
            image = self.transform(image)
        if self.target_transform:
            label = self.target_transform(label)
        return image, label

In [ ]:
CustomTranslationDataset

__main__.CustomTranslationDataset

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['translation'],
        num_rows: 1659083
    })
    validation: Dataset({
        features: ['translation'],
        num_rows: 520
    })
    test: Dataset({
        features: ['translation'],
        num_rows: 2507
    })
})

In [ ]:
class CustomTranslationDataset(Dataset):
    def __init__(self, dataset, tokenizer, split='train'):
        self.dataset = dataset
        self.tokenizer = tokenizer
        self.split = split
        self.tokenized_data = self.tokenize_data()

    def tokenize_data(self):
        tokens = []
        for i in self.dataset[self.split]['translation']:
            en_tokens = self.tokenizer.encode(i['en']).ids
            hi_tokens = self.tokenizer.encode(i['hi']).ids
            tokens.append((en_tokens, hi_tokens))
        return tokens

    def __getitem__(self, idx):
        return self.tokenized_data[idx]

    def __len__(self):
        return len(self.tokenized_data)

In [ ]:
ds = CustomTranslationDataset(dataset, tokenizer)

In [ ]:
for i in ds:
    print(i)
    break

([12879, 593, 2865, 388, 20185, 872, 678], [1435, 207, 421, 230, 237, 208, 721, 217, 244, 210, 217, 543, 891, 679, 213, 575, 205, 252, 208, 219, 205, 219, 205, 223, 210, 205, 277, 205, 316, 271, 246])


In [ ]:
for i in ds:
    print(tokenizer.decode(i[0]))
    print(len(tokenizer.decode(i[1])))
    print(len(i[1]))
    break

Give your application an accessibility workout
47
31


In [ ]:
from datasets import load_dataset
from tokenizers import Tokenizer, models, trainers, pre_tokenizers, decoders, processors

dataset = load_dataset("cfilt/iitb-english-hindi")

def get_texts(dataset, lang):
    for example in dataset['train']['translation']:
        yield example[lang]

tokenizer_en = Tokenizer(models.BPE())
tokenizer_en.pre_tokenizer = pre_tokenizers.ByteLevel(add_prefix_space=False)
tokenizer_en.decoder = decoders.ByteLevel()
tokenizer_en.post_processor = processors.ByteLevel()
trainer = trainers.BpeTrainer(special_tokens=["<s>", "<pad>", "</s>", "<unk>", "<mask>"])
tokenizer_en.train_from_iterator(get_texts(dataset, 'en'), trainer=trainer)

tokenizer_en.save("iitb-english-hindi-tokenizer_en.json")

tokenizer_hi = Tokenizer(models.BPE())
tokenizer_hi.pre_tokenizer = pre_tokenizers.ByteLevel(add_prefix_space=False)
tokenizer_hi.decoder = decoders.ByteLevel()
tokenizer_hi.post_processor = processors.ByteLevel()
trainer = trainers.BpeTrainer(special_tokens=["<s>", "<pad>", "</s>", "<unk>", "<mask>"])
tokenizer_hi.train_from_iterator(get_texts(dataset, 'hi'), trainer=trainer)

tokenizer_hi.save("iitb-english-hindi-tokenizer_hi.json")

In [ ]:
tokenizer.get_vocab_size()

30000

In [ ]:
max_len=5000
# position = torch.arange(max_len).unsqueeze(1)
position = torch.zeros((max_len,10))
position = torch.zeros((max_len,10)).unsqueeze(1)
position.shape

torch.Size([5000, 1, 10])

In [ ]:
m = nn.Softmax(dim=-1)
input = torch.randn(2, 3)
print(input)
output = m(input)
print(output)

tensor([[-0.8562, -1.3840,  0.0435],
        [-1.3955, -0.0956, -0.2893]])
tensor([[0.2470, 0.1457, 0.6073],
        [0.1300, 0.4770, 0.3930]])


In [ ]:
from torch import nn
import numpy as np

In [ ]:
# output = tokenizer.encode_batch(["Hello, y'all!", "How are you 😁 ?"])
output = tokenizer.encode_batch(["Hello, y'all!", "Hello, y'all!"])
output = [x.ids for x in output]
print(output)
torch.Tensor(output).shape

[[14823, 83, 16, 325, 11, 465, 5], [14823, 83, 16, 325, 11, 465, 5]]


torch.Size([2, 7])

In [ ]:
class PositionalEncoding(nn.Module):
    def __init__(self) -> None:
        super(PositionalEncoding,self).__init__()

    def forward(self,x):
        return x

In [ ]:
class Decoder(nn.Module):
    def __init__(self) -> None:
        super(Decoder, self).__init__()

    def forward(self,x):
        return x

In [ ]:
class Encoder(nn.Module):
    def __init__(self, d, dk, dv, h) -> None:
        super(Encoder, self).__init__()
        # self.query_weight = nn.Parameter(torch.randn(d, dk), requires_grad=True)
        # self.key_weight   = nn.Parameter(torch.randn(d, dk), requires_grad=True)
        # self.value_weight = nn.Parameter(torch.randn(d, dv), requires_grad=True)
        self.query_layer = nn.Linear(d,dk)
        self.key_layer = nn.Linear(d,dk)
        self.value_layer = nn.Linear(d,dv)
        self.output_layer = nn.Linear(h*dv,d)
        self.dk = dk
        self.h = h
        self.layer_norm1 = nn.LayerNorm(d)
        self.layer_norm2 = nn.LayerNorm(d)
        self.ff = nn.Linear()


    def multihead_attention(self, query, key, value):
        # same layers???
        head_outputs = []
        for _ in range(self.h):
            head_output = self.self_attention(query, key, value)
            head_outputs.append(head_output)
        return torch.concat(head_outputs, dim=-1)

    def self_attention(self, query, key, value):
        qt = torch.bmm(query, torch.transpose(key,1,2))
        attn_weights = nn.Softmax(dim=-1)(qt/np.sqrt(self.dk))
        self_attn = torch.bmm(qt, value)
        return self_attn

    def forward(self,x):
        # query = torch.matmul(x, self.query_weight)
        # key   = torch.matmul(x, self.key_weight)
        # value = torch.matmul(x, self.value_weight)

        query = self.query_layer(x)
        key   = self.key_layer(x)
        value = self.value_layer(x)

        multihead_attn = self.multihead_attention(query, key, value)
        output = self.output_layer(multihead_attn)
        resi1 = output + x
        norm1 = self.layer_norm1(resi1)

        return resi

In [ ]:
class Transformer(nn.Module):
    def __init__(self, tokenizer, nx=6) -> None:
        super(Transformer, self).__init__()
        self.tokenizer = tokenizer
        self.nx = nx
        self.d = 256
        self.dk = 512
        self.dv = 512
        self.h = 8
        self.inp_embedding = nn.Embedding(tokenizer.get_vocab_size(), self.d, max_norm=True)
        self.positional_encoding = PositionalEncoding()
        self.encoder = Encoder(d = self.d, dk = self.dk, dv = self.dv, h = self.h)
        self.decoder = Decoder()

    def forward(self, input_tokens):
        x = self.inp_embedding(input_tokens)
        x = self.positional_encoding(x)
        for _ in range(self.nx):
            x = self.encoder(x)
            print(x.shape)
        # for _ in range(self.nx):
        #     x = self.decoder(x)
        return x

In [ ]:
trans = Transformer(tokenizer)(torch.LongTensor(output))

torch.Size([2, 7, 256])
torch.Size([2, 7, 256])
torch.Size([2, 7, 256])
torch.Size([2, 7, 256])
torch.Size([2, 7, 256])
torch.Size([2, 7, 256])


In [ ]:
torch.Tensor(output)

tensor([[1.4823e+04, 8.3000e+01, 1.6000e+01, 3.2500e+02, 1.1000e+01, 4.6500e+02,
         5.0000e+00],
        [1.4823e+04, 8.3000e+01, 1.6000e+01, 3.2500e+02, 1.1000e+01, 4.6500e+02,
         5.0000e+00]])

In [ ]:
torch.LongTensor(output)

tensor([[14823,    83,    16,   325,    11,   465,     5],
        [14823,    83,    16,   325,    11,   465,     5]])

In [ ]:
np.array(output, dtype=np.int32)

array([[14823,    83,    16,   325,    11,   465,     5],
       [14823,    83,    16,   325,    11,   465,     5]], dtype=int32)

In [ ]:
nn.Linear(10,10)

Linear(in_features=10, out_features=10, bias=True)

In [ ]:
l = nn.Linear(10,20)

In [ ]:
x = torch.randn(128, 32,10)
x.shape

torch.Size([128, 32, 10])

In [ ]:
l(x).shape

torch.Size([128, 32, 20])

In [ ]:
l(x).size()

torch.Size([32, 20])